template: fareoffice/rig-templates/simple-app
version: 0.1.0
parameters:
  name: ''
  namespace: ''
  replicas: 2
  image: ''
  port: 80
  readinessPath: /health
  cpuMin: 500m
  cpuMax: 1000m
  memory: 800mi
  environmentSecretRefs: ''
  dnsName: ''
  imageTag: ''
