apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{name}}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    spec:
      containers:
      - name: {{name}}
        resources:
          requests:
            cpu: 300
            memory: 300
          limits:
            cpu: 300
            memory: 300
        image: image
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: defaults
            optional: true
        ports:
        - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 20
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            port: 80
            path: /health
          initialDelaySeconds: 20
          timeoutSeconds: 3
