apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{name}}
spec:
  replicas: {{replicas}}
  selector:
    matchLabels:
      app: {{name}}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    spec:
      containers:
      - name: {{name}}
        resources:
          requests:
            cpu: {{cpuMin}}
            memory: {{memoryMin}}
          limits:
            cpu: {{cpuMax}}
            memory: {{memoryMax}}
        image: {{image}}
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: defaults
            optional: true
        ports:
        - containerPort: {{port}}
        livenessProbe:
          tcpSocket:
            port: {{port}}
          initialDelaySeconds: 20
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            port: 80
            path: {{readinessPath}}
          initialDelaySeconds: 20
          timeoutSeconds: 3
