
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{name}}
  annotations:
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/acme-dns01-provider: route53
    certmanager.k8s.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "false"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec:
  rules:
  - host: {{name}}.int.fareonline.net
    http:
      paths:
      - path: "/"
        backend:
          serviceName: {{name}}
          servicePort: 80
  tls:
  - hosts:
    - {{name}}.int.fareonline.net
    secretName: {{name}}-tls

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{name}}
spec:
  podSelector:
    matchLabels:
      app: {{name}}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
